### ISSUE TITLE
Upload to PVoutput fails with Unauthorized 401: Invalid System ID

### ISSUE THREAD

**Issue by GoogleCodeExporter** [solmoller/eversolar-monitor#9] opened 2015-08-20 17:46 UTC
```
What steps will reproduce the problem?
1.Retry the upload
2.
3.

What is the expected output? What do you see instead?
That the upload will be succesfull :)

What version of the product are you using? On what operating system?
I'm using the diskimage file for the raspberry Pi version 0.14 of the script.

Please provide any additional information below.

I've attached the log from the monitor script. My pvoutput ID is 37495 
(http://pvoutput.org/list.jsp?sid=37495)

Below the line with systemid's in eversolar.ini
system_id XH30006011530011 = 37495

I have only 1 inverter.
```

Original issue reported on code.google.com by `An...@klinkonline.nl` on 31 May 2015 at 3:06

Attachments:
* [eversolar.txt](https://storage.googleapis.com/google-code-attachments/eversolar-monitor/issue-9/comment-0/eversolar.txt)

**Comment by StephenE** [comment] 2015-08-22 08:39
I'm also getting this issue. I added some logging around the call to curl to dump out the key variables, and it seems that the system id isn't being found in the hash. I used the following code:

    use Data::Dumper;
    print Dumper(\$config->pvoutput_system_id);
    pmu_log("Key ".$pvoutput_api_key." system_id: ".$this_pvoutput_system_id);
    pmu_log("System Id: ".$inverters{$inverter}{"serial"});
                
Which I used to infer the following values for the variables

$config->pvoutput_system_id: = \{
            'EL36806011540195' => '40124'
          };
$this_pvoutput_system_id = 
$inverters{$inverter}{"serial"} = EL36806011540195

I don't know Perl, so I don't understand why it doesn't seem to be finding the entry in the hash despite the fact they look the same to me. My eversolar.ini config file looks like this:

system_id EL36806011540195 = 40124

**Comment by StephenE** [comment] 2015-08-23 13:14
I got my upload to PVOutput to work by hard coding the system_id in the Perl script. This won't "fix" whatever the underlying issue is, but allowed me to start viewing my data!

**Comment by solmoller** [comment] 2015-08-24 18:00
Just a hunch - could there comehow be something that looks like an escape character in your serial number?


Henrik

**Comment by StephenE** [comment] 2015-08-25 06:52
Not that I can immediately see, but I'm not a Perl expert. I'll try and find some time to capture the packets that get sent back & forth - perhaps that'll help reproduce the issue reliably

**Comment by solmoller** [comment] 2015-08-25 20:19
Try having perl count the number of characters in the string...

**Comment by StephenE** [comment] 2015-08-27 19:39
I've traced this further and it's somehow related to the same fundamental issue that causes issue #10. Something is adding two extra characters to the serial number of my inverter when booting with a fresh database. This issue doesn't occur if you have an existing database because the serial id comes from the database and not the inverter. See my latest post on issue #10 for more details

**Comment by solmoller** [comment] 2015-09-02 18:57
CLosing as per issue #10

**Closed by solmoller** 2015-09-02 18:57 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
